### ISSUE TITLE
Too many connectionsが一体なになのかを調査する

### ISSUE THREAD

**Issue by ArkArk** [voyagegroup/hakaru201911-team-c#14]
# アプローチ

```
http: panic serving 10.1.3.25:43364: Error 1040: Too many connections
```
とエラーが出るが、connectionが何を指しているのか。

## 想定インパクト

* 次のアプローチを整理する上で助けになる
* 優先度は高いと思う

## モニタリング項目

* なし

## 結果/考察

*

**Comment by ArkArk** [comment]
`db.Open`はアプリの起動時に一度しか行っていないはずなので、DBへのconnectionは1回なのでは？？？と思ってるがtoo many connectionと出ているので自分の理解が間違えてそう

**Comment by mizuho1998** [comment]
https://golang.org/pkg/database/sql/#Open

**Comment by k-nasa** [comment]
同じく。認識間違えてると辛い、、、
前に貼ったグラフは平均を見てしまっていました。
合計だと、こんな感じ。10個ありますね

<img width="1163" alt="スクリーンショット 2019-11-03 13 30 12" src="https://user-images.githubusercontent.com/23740172/68080403-17121800-fe3e-11e9-803e-492289c678f4.png">

**Comment by ArkArk** [comment]
> Open may just validate its arguments without creating a connection to the database. To verify that the data source name is valid, call Ping.

つまり、`db.Open`はconnectionをつくってるのではなく、pingを読んでverifyしてるだけ

**Comment by k-nasa** [comment]
Gopath配下でgrep 'Too many connections'してみた。
DBに関するエラーメッセージだと思う。

<img width="784" alt="スクリーンショット 2019-11-03 13 36 40" src="https://user-images.githubusercontent.com/23740172/68080447-f9917e00-fe3e-11e9-88a2-bff3bfd61a6d.png">

connectionsが貼られるタイミング。connectionsとは。はこれから調べていきます

**Comment by ArkArk** [comment]
https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1131

実際にconnectionをつくっている箇所

**Comment by k-nasa** [comment]
Execを潜っていくとココに行くので、Execのたびに新しいコネクション接続が行われている。

これがconnection-poolの参考になるかも？
https://golang.shop/post/go-databasesql-10-connection-pool-ja/

**Comment by mizuho1998** [comment]
`lsof -i`のログ


COMMAND    PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
hakaru    1051   root    3u  IPv6  824811      0t0  TCP *:tproxy (LISTEN)
hakaru    1051   root    4u  IPv6 1152684      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:37702 (ESTABLISHED)
hakaru    1051   root    8u  IPv6 1157843      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40758 (ESTABLISHED)
hakaru    1051   root   10u  IPv6 1157844      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40760 (ESTABLISHED)
hakaru    1051   root   11u  IPv6 1151017      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:36884 (ESTABLISHED)
hakaru    1051   root   12u  IPv6 1156968      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40690 (ESTABLISHED)
hakaru    1051   root   13u  IPv6 1157018      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40738 (ESTABLISHED)
hakaru    1051   root   14u  IPv6 1156068      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40124 (ESTABLISHED)
hakaru    1051   root   15u  IPv6 1156757      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40560 (ESTABLISHED)
hakaru    1051   root   16u  IPv6 1157322      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40424 (ESTABLISHED)
hakaru    1051   root   18u  IPv6 1157020      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40740 (ESTABLISHED)
hakaru    1051   root   22u  IPv6 1102128      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:29502 (ESTABLISHED)
hakaru    1051   root   23u  IPv6 1068972      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:11460 (ESTABLISHED)
hakaru    1051   root   24u  IPv6 1157021      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40742 (ESTABLISHED)
hakaru    1051   root   25u  IPv6 1155788      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:39714 (ESTABLISHED)
hakaru    1051   root   27u  IPv6 1156848      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40646 (ESTABLISHED)
hakaru    1051   root   28u  IPv6 1156418      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40304 (ESTABLISHED)
hakaru    1051   root   29u  IPv6 1157453      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40510 (ESTABLISHED)
hakaru    1051   root   32u  IPv4 1157766      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:33708->ip-10-1-13-216.ap-northeast-1.compute.internal:mysql (ESTABLISHED)
hakaru    1051   root   33u  IPv6 1156849      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40648 (ESTABLISHED)
hakaru    1051   root   36u  IPv6 1157845      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40762 (ESTABLISHED)
hakaru    1051   root   37u  IPv6 1156773      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40572 (ESTABLISHED)
hakaru    1051   root   38u  IPv6 1157846      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40764 (ESTABLISHED)
hakaru    1051   root   39u  IPv6 1154988      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:39988 (ESTABLISHED)
hakaru    1051   root   40u  IPv6 1143851      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:32018 (ESTABLISHED)
hakaru    1051   root   42u  IPv6 1157025      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40744 (ESTABLISHED)
hakaru    1051   root   43u  IPv6 1157847      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40766 (ESTABLISHED)
hakaru    1051   root   44u  IPv6 1157848      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40768 (ESTABLISHED)
hakaru    1051   root   47u  IPv6 1156680      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40528 (ESTABLISHED)
hakaru    1051   root   48u  IPv6 1157849      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40770 (ESTABLISHED)
hakaru    1051   root   51u  IPv4 1158285      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:33742->ip-10-1-13-216.ap-northeast-1.compute.internal:mysql (ESTABLISHED)
hakaru    1051   root   52u  IPv6 1156666      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40516 (ESTABLISHED)
hakaru    1051   root   53u  IPv6 1114589      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:10876 (ESTABLISHED)
hakaru    1051   root   54u  IPv6 1143854      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:32024 (ESTABLISHED)
hakaru    1051   root   55u  IPv6 1100384      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:29054 (ESTABLISHED)
hakaru    1051   root   60u  IPv6 1143855      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:32026 (ESTABLISHED)
hakaru    1051   root   64u  IPv6 1156864      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40652 (ESTABLISHED)
hakaru    1051   root   65u  IPv6 1157454      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40508 (ESTABLISHED)
hakaru    1051   root   68u  IPv6 1143857      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:32030 (ESTABLISHED)
hakaru    1051   root   71u  IPv6 1143858      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:32032 (ESTABLISHED)
hakaru    1051   root   80u  IPv6 1156330      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40236 (ESTABLISHED)
hakaru    1051   root   81u  IPv6 1156862      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40650 (ESTABLISHED)
hakaru    1051   root   82u  IPv6 1049755      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:59772 (ESTABLISHED)
hakaru    1051   root   87u  IPv6 1156290      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40220 (ESTABLISHED)
hakaru    1051   root   88u  IPv6 1141697      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:31634 (ESTABLISHED)
hakaru    1051   root   98u  IPv6 1150600      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:36776 (ESTABLISHED)
hakaru    1051   root  100u  IPv6 1156700      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40532 (ESTABLISHED)
hakaru    1051   root  102u  IPv6 1150415      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:36636 (ESTABLISHED)
hakaru    1051   root  107u  IPv6 1156428      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40316 (ESTABLISHED)
hakaru    1051   root  109u  IPv6 1049761      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:59788 (ESTABLISHED)
hakaru    1051   root  112u  IPv6 1101040      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:29310 (ESTABLISHED)
hakaru    1051   root  114u  IPv6 1049763      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:59792 (ESTABLISHED)
hakaru    1051   root  120u  IPv6 1157264      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40404 (ESTABLISHED)
hakaru    1051   root  121u  IPv6 1157381      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40474 (ESTABLISHED)
hakaru    1051   root  122u  IPv6 1101489      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:29608 (ESTABLISHED)
hakaru    1051   root  123u  IPv6 1157223      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40398 (ESTABLISHED)
hakaru    1051   root  125u  IPv6 1141679      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:31624 (ESTABLISHED)
hakaru    1051   root  128u  IPv6 1141709      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:31658 (ESTABLISHED)
hakaru    1051   root  139u  IPv6 1100396      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:29068 (ESTABLISHED)
hakaru    1051   root  148u  IPv6 1156881      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40658 (ESTABLISHED)
hakaru    1051   root  150u  IPv6 1157397      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40486 (ESTABLISHED)
hakaru    1051   root  151u  IPv6 1157399      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40488 (ESTABLISHED)
hakaru    1051   root  152u  IPv6 1156884      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40662 (ESTABLISHED)
hakaru    1051   root  156u  IPv6 1154692      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:39782 (ESTABLISHED)
hakaru    1051   root  161u  IPv6 1151188      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:37304 (ESTABLISHED)
hakaru    1051   root  162u  IPv6 1150419      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:36640 (ESTABLISHED)
hakaru    1051   root  169u  IPv6 1156788      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40584 (ESTABLISHED)
hakaru    1051   root  171u  IPv6 1156891      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40664 (ESTABLISHED)
hakaru    1051   root  172u  IPv6 1157478      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40540 (ESTABLISHED)
hakaru    1051   root  181u  IPv6 1158344      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40746 (ESTABLISHED)
hakaru    1051   root  182u  IPv6 1158348      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40748 (ESTABLISHED)
hakaru    1051   root  189u  IPv6 1070406      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:12774 (ESTABLISHED)
hakaru    1051   root  191u  IPv6 1128509      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:22742 (ESTABLISHED)
hakaru    1051   root  194u  IPv6 1156494      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40358 (ESTABLISHED)
hakaru    1051   root  195u  IPv6 1157552      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40688 (ESTABLISHED)
hakaru    1051   root  198u  IPv6 1156495      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40360 (ESTABLISHED)
hakaru    1051   root  199u  IPv6 1156807      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40616 (ESTABLISHED)
hakaru    1051   root  200u  IPv6 1148167      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:34580 (ESTABLISHED)
hakaru    1051   root  201u  IPv6 1156809      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40618 (ESTABLISHED)
hakaru    1051   root  203u  IPv6 1147344      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:34340 (ESTABLISHED)
hakaru    1051   root  213u  IPv6 1157354      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40442 (ESTABLISHED)
hakaru    1051   root  220u  IPv6 1141494      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:31530 (ESTABLISHED)
hakaru    1051   root  222u  IPv6 1156096      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40174 (ESTABLISHED)
hakaru    1051   root  223u  IPv6 1157568      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40692 (ESTABLISHED)
hakaru    1051   root  227u  IPv6 1111916      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:11988 (ESTABLISHED)
hakaru    1051   root  234u  IPv6 1152283      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:37264 (ESTABLISHED)
hakaru    1051   root  239u  IPv6 1141731      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:31702 (ESTABLISHED)
hakaru    1051   root  243u  IPv6 1098413      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:28320 (ESTABLISHED)
hakaru    1051   root  245u  IPv6 1098414      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:28322 (ESTABLISHED)
hakaru    1051   root  250u  IPv6 1157569      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40694 (ESTABLISHED)
hakaru    1051   root  251u  IPv6 1111919      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:11994 (ESTABLISHED)
hakaru    1051   root  261u  IPv6 1128383      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:22832 (ESTABLISHED)
hakaru    1051   root  262u  IPv6 1098431      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:28338 (ESTABLISHED)
hakaru    1051   root  268u  IPv6 1050706      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:59552 (ESTABLISHED)
hakaru    1051   root  270u  IPv6 1111920      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:11996 (ESTABLISHED)
hakaru    1051   root  275u  IPv6 1156984      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40712 (ESTABLISHED)
hakaru    1051   root  277u  IPv6 1148169      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:34582 (ESTABLISHED)
hakaru    1051   root  279u  IPv6 1148357      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:34708 (ESTABLISHED)
hakaru    1051   root  281u  IPv6 1156988      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40714 (ESTABLISHED)
hakaru    1051   root  283u  IPv6 1156994      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40722 (ESTABLISHED)
hakaru    1051   root  288u  IPv6 1156995      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40720 (ESTABLISHED)
hakaru    1051   root  290u  IPv6 1098454      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:28352 (ESTABLISHED)
hakaru    1051   root  297u  IPv6 1152057      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:37084 (ESTABLISHED)
hakaru    1051   root  298u  IPv6 1111925      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:dbisamserver2 (ESTABLISHED)
hakaru    1051   root  300u  IPv6 1156838      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:40638 (ESTABLISHED)
hakaru    1051   root  306u  IPv6 1062195      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:6440 (ESTABLISHED)
hakaru    1051   root  312u  IPv6 1062199      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:6452 (ESTABLISHED)
hakaru    1051   root  316u  IPv6 1098469      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:28366 (ESTABLISHED)
hakaru    1051   root  318u  IPv6 1098471      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:28368 (ESTABLISHED)
hakaru    1051   root  320u  IPv6 1062204      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:6462 (ESTABLISHED)
hakaru    1051   root  325u  IPv6 1062209      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:6472 (ESTABLISHED)
hakaru    1051   root  350u  IPv6 1062219      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:6492 (ESTABLISHED)
hakaru    1051   root  371u  IPv6 1111931      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:12018 (ESTABLISHED)
hakaru    1051   root  383u  IPv6 1128729      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:23162 (ESTABLISHED)
hakaru    1051   root  405u  IPv6 1111934      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:12024 (ESTABLISHED)
hakaru    1051   root  410u  IPv6 1111936      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:12028 (ESTABLISHED)
hakaru    1051   root  417u  IPv6 1128746      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:23196 (ESTABLISHED)
hakaru    1051   root  423u  IPv6 1128747      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:23200 (ESTABLISHED)
hakaru    1051   root  430u  IPv6 1128751      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:23198 (ESTABLISHED)
hakaru    1051   root  569u  IPv6 1070970      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:13434 (ESTABLISHED)
hakaru    1051   root  572u  IPv6 1070972      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:13438 (ESTABLISHED)
hakaru    1051   root  578u  IPv6 1114940      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:11198 (ESTABLISHED)
hakaru    1051   root  615u  IPv6 1070986      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:13468 (ESTABLISHED)
hakaru    1051   root  678u  IPv6 1111977      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:12110 (ESTABLISHED)
hakaru    1051   root  682u  IPv6 1111978      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:12108 (ESTABLISHED)
hakaru    1051   root  687u  IPv6 1114947      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:11216 (ESTABLISHED)
hakaru    1051   root  728u  IPv6 1051049      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:59962 (ESTABLISHED)
hakaru    1051   root  791u  IPv6 1115033      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-1-194.ap-northeast-1.compute.internal:11234 (ESTABLISHED)
hakaru    1051   root  815u  IPv6  999064      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:tproxy->ip-10-1-3-14.ap-northeast-1.compute.internal:58330 (ESTABLISHED)
ssm-sessi 1551   root   22u  IPv4  990192      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:40814->ip-10-1-5-45.ap-northeast-1.compute.internal:https (ESTABLISHED)
ssm-sessi 1566   root   24u  IPv4  992281      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:54074->ip-10-1-3-233.ap-northeast-1.compute.internal:https (ESTABLISHED)
rpcbind   1909    rpc    6u  IPv4   15794      0t0  UDP *:sunrpc
rpcbind   1909    rpc    7u  IPv4   15795      0t0  UDP *:807
rpcbind   1909    rpc    8u  IPv4   15796      0t0  TCP *:sunrpc (LISTEN)
rpcbind   1909    rpc    9u  IPv6   15797      0t0  UDP *:sunrpc
rpcbind   1909    rpc   10u  IPv6   15798      0t0  UDP *:807
rpcbind   1909    rpc   11u  IPv6   15799      0t0  TCP *:sunrpc (LISTEN)
chronyd   1912 chrony    1u  IPv4   15813      0t0  UDP localhost:323
chronyd   1912 chrony    2u  IPv6   15814      0t0  UDP localhost6:323
dhclient  2166   root    6u  IPv4   16227      0t0  UDP *:bootpc
dhclient  2281   root    5u  IPv6   17817      0t0  UDP ip-10-1-13-89.ap-northeast-1.compute.internal:dhcpv6-client
master    2424   root   13u  IPv4   19509      0t0  TCP localhost:smtp (LISTEN)
amazon-ss 2469   root    8u  IPv4 1158540      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:57502->ip-10-1-1-118.ap-northeast-1.compute.internal:https (ESTABLISHED)
amazon-ss 2469   root   11u  IPv4   19399      0t0  TCP ip-10-1-13-89.ap-northeast-1.compute.internal:39246->ip-10-1-3-233.ap-northeast-1.compute.internal:https (ESTABLISHED)
sshd      2521   root    3u  IPv4   20189      0t0  TCP *:ssh (LISTEN)
sshd      2521   root    4u  IPv6   20191      0t0  TCP *:ssh (LISTEN)

**Comment by ArkArk** [comment]
- MySQLとのconnectは2つあるが、ほとんどはそれ以外
    - ELBとの接続と思われる

too many connectionsの原因として、
ELBとの接続が多いせいで、OS自体の同時接続数を超えたためにDBとの新しい接続ができなくなっていると考えられる。

**Comment by ArkArk** [comment]
## ELBとの同時接続数を減らすには？

大まかな方針として下の２つがある：

- 1requestあたりのresponseまでの時間を短くする
- アプリ側をスケールアウトする
