### ISSUE TITLE
スケールアウトする

### ISSUE THREAD

**Issue by k-nasa** [voyagegroup/hakaru201911-team-c#15]
# アプローチ
インスタンスをいくつか立ててスケールアウトする(10台とか5台とか？)

https://github.com/voyagegroup/hakaru201911-team-c/issues/14#issuecomment-549106421

## 想定インパクト
中。
LBのターゲットが現状１つしか無いが、ターゲットを増やすことでより捌けるようにする。

**Comment by Kase076** [comment]
AutoScallingGroupを使ってインスタンスを10個作り、動作を確認

シナリオ１での結果
https://sunrise201911-team-c-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-1043865531.ap-northeast-1.elb.amazonaws.com%3A80/20191103-1429/report.html
