### ISSUE TITLE
db.Execを非同期で行う

### ISSUE THREAD

**Issue by ArkArk** [voyagegroup/hakaru201911-team-c#17]
# アプローチ

`db.Exec`を非同期で行う

- 現状ではresponseまでの処理時間のボトルネックがDBへのwriteだと思われる
- write部分は非同期で行い、すぐにresponseを返すと良さそう

## 想定インパクト

* ref. https://github.com/voyagegroup/hakaru201911-team-c/issues/14#issuecomment-549106421
* 単純に1 requestあたりのresponseまでの時間が短くなるので、同時接続数が減ると思われる
* インパクトは比較的大きいのでは

## モニタリング項目

* 1 秒あたりのリクエスト処理数
* 200/5XXのそれぞれの個数

## 結果/考察

*

**Comment by k-nasa** [comment]
```golnag
	hakaruHandler := func(w http.ResponseWriter, r *http.Request) {
		name := r.URL.Query().Get("name")
		value := r.URL.Query().Get("value")

		go func() {
			_, e := db.Exec("INSERT INTO eventlog(at, name, value) values(NOW(), ?, ?)", name, value)
			if e != nil {
				panic(e.Error())
			}
		}()

		origin := r.Header.Get("Origin")
		if origin != "" {
.....
```

**Comment by mizuho1998** [comment]
シナリオ1

## before
![スクリーンショット 2019-11-03 16 16 14](https://user-images.githubusercontent.com/39789796/68081792-d246ab00-fe56-11e9-9022-31c28b5876eb.png)

https://sunrise201911-team-c-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-1043865531.ap-northeast-1.elb.amazonaws.com%3A80/20191103-1611/report.html

## after 
![スクリーンショット 2019-11-03 16 28 00](https://user-images.githubusercontent.com/39789796/68081802-ed191f80-fe56-11e9-9148-e0c87ab2f7d1.png)

https://sunrise201911-team-c-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-1043865531.ap-northeast-1.elb.amazonaws.com%3A80/20191103-1619/report.html
