### ISSUE TITLE
DBのMax connectionsを増やす

### ISSUE THREAD

**Issue by k-nasa** [voyagegroup/hakaru201911-team-c#20]
増やす
分量は、consoleからみたmax_connectionsにする
<img width="826" alt="スクリーンショット 2019-11-03 15 33 01" src="https://user-images.githubusercontent.com/23740172/68081303-4b420480-fe4f-11e9-8e17-56a79061128e.png">

**Comment by mizuho1998** [comment]
## after

シナリオ１
![スクリーンショット 2019-11-03 15 59 47](https://user-images.githubusercontent.com/39789796/68081557-1f288280-fe53-11e9-9240-26129b920147.png)

99.7%
