### ISSUE TITLE
NetworkTrafficとエラーの相関関係を調べる

### ISSUE THREAD

**Issue by Kase076** [voyagegroup/hakaru201911-team-c#24]
# アプローチ
kakeruのログからNetworkTrafficとエラーの相関関係がありそうなことがわかったので調べる
![image](https://user-images.githubusercontent.com/38277210/68081879-6c5b2300-fe58-11e9-89f4-8bb18405a9b0.png)
![image](https://user-images.githubusercontent.com/38277210/68081888-7715b800-fe58-11e9-954b-fb2050a27db3.png)

## 想定インパクト
502エラーの原因の究明

## モニタリング項目
panicの発生箇所

**Comment by Kase076** [comment]
過去にも出てる例あり
![image](https://user-images.githubusercontent.com/38277210/68081905-c4922500-fe58-11e9-83f3-343f2b597210.png)
![image](https://user-images.githubusercontent.com/38277210/68081910-d1167d80-fe58-11e9-94ab-2587082b7f9d.png)

**Comment by mizuho1998** [comment]
- hakaruの`/var/log/messages`を確認
- hakaruのプロセスが死んでいた

**Comment by ArkArk** [comment]
## 仮説

goroutineを立てすぎているのかもしれない
