### ISSUE TITLE
シナリオ2 504エラーがかなり出る

### ISSUE THREAD

**Issue by Kase076** [voyagegroup/hakaru201911-team-c#27]
# アプローチ
ログあたりを見て504エラーの原因を探る
原因を排除する

## 想定インパクト
504エラーがなくなる

## モニタリング項目
CloudWatchのログ
他

**Comment by Kase076** [comment]
![image](https://user-images.githubusercontent.com/38277210/68095645-7af41980-feee-11e9-9897-adfec02f2591.png)

**Comment by Kase076** [comment]
```
18:42:03
Nov 3 18:42:03 ip-10-1-13-21 hakaru: 2019/11/03 09:42:03 http: Accept error: accept tcp [::]:8081: accept4: too many open files; retrying in 5ms
```

**Comment by ArkArk** [comment]
## 仮説

恐らくTCPの同時接続数が膨大になっているせい

- つまり、ELBとの同時接続数
