### ISSUE TITLE
kakeru multinode

### ISSUE THREAD

**Issue by shomah4a** [voyagegroup/hakaru201911-team-c#30]
やりかた

ssm で kakeru-worker にログインする
```
$ sudo su ubuntu
$ cd /opt/kakeru
$ make -C app kakeru/multinode HOST=hakaru-1043865531.ap-northeast-1.elb.amazonaws.com SCENARIO=2
```

かけるのノードを増やすとき
- autoscaling group の kakeru の台数を増やす
- 同じようにかける

**Comment by shomah4a** [comment]
https://sunrise201911-team-c-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-1043865531.ap-northeast-1.elb.amazonaws.com%3A80/20191104-1305/report.html

**Comment by k-nasa** [comment]
ログインするkakeru-workerはどれでも良い。

**Comment by shomah4a** [comment]
ake -C app kakeru/multinode HOST=hakaru-1043865531.ap-northeast-1.elb.amazonaws.com SCENARIO=2
