### ISSUE TITLE
hakaruの台数を増やす

### ISSUE THREAD

**Issue by Kase076** [voyagegroup/hakaru201911-team-c#33]
安定させたい
https://sunrise201911-team-c-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-1043865531.ap-northeast-1.elb.amazonaws.com%3A80/20191104-1432/report.html#stats
![image](https://user-images.githubusercontent.com/38277210/68101705-5316ad00-ff12-11e9-8f6f-323a5fc065ef.png)

# アプローチ

hakaruのスケールアウトを行う

## 想定インパクト

* スループットが安定する可能性がある

## モニタリング項目

* 5xxの割合
* redash
* スループットのグラフ

**Comment by Kase076** [comment]
DBのSetMaxConnectionの設定が必要
現在は66

**Comment by Kase076** [comment]
hakaru 3台で実行

https://sunrise201911-team-c-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-1043865531.ap-northeast-1.elb.amazonaws.com%3A80/20191104-1501/graph.html#response_time

![image](https://user-images.githubusercontent.com/38277210/68102150-b7d30700-ff14-11e9-83f8-f2c1504cf985.png)

**Comment by Kase076** [comment]
Response Time は安定していた
![image](https://user-images.githubusercontent.com/38277210/68103425-2070b280-ff1a-11e9-9efc-f5fc7faa96f8.png)

**Comment by ArkArk** [comment]
スケーリングできたことを確認できた
