### ISSUE TITLE
DBのconnectionを一つにする

### ISSUE THREAD

**Issue by ArkArk** [voyagegroup/hakaru201911-team-c#5]
# アプローチ

Before:

ソースコードの`sql.Open`がResponseが来るたびに行っている。

After:

アプリ起動後に1度のみ行う

PR: https://github.com/voyagegroup/hakaru201911-team-c/pull/4

## 想定インパクト

- エラー原因が変わる
- 5系のresponseが減る

## モニタリング項目

- Cloud Watchのlogのpanic箇所
- kakeruくんのレポート結果

## 結果/考察

- hakaru側のエラー文が変わった
- 5系の数が1万程度減った

**Comment by k-nasa** [comment]
## Before
![スクリーンショット 2019-11-02 16 59 24](https://user-images.githubusercontent.com/23740172/68068088-6b60bd80-fd94-11e9-8495-55cec06c3400.png)

## After
![スクリーンショット 2019-11-02 16 59 17](https://user-images.githubusercontent.com/23740172/68068089-6b60bd80-fd94-11e9-83c6-afbffe761649.png)
