### ISSUE TITLE
遅延insertしても良いのでは？

### ISSUE THREAD

**Issue by k-nasa** [voyagegroup/hakaru201911-team-c#7]
# アプローチ
毎回insert書き込まなくても、まとめてinsertとかでも良いかも

## 想定インパクト

毎回書き込まなくてもいいので、実装できれば割と早くなりそう。
DBアクセス周りも減るので。

**Comment by k-nasa** [comment]
まとめてinsertするために、結局、どんなパラメータが送られていたのかを保存しとかないといけないので、そこをどうするかという問題はある。
DBより早いのを用意できれば、それに一時書き込みしておいて、あとからDBに反映するとかで行けそう。
job queueミタイなのを使うとか。

**Comment by mizuho1998** [comment]
goroutine と channel を使って実装
channelはリクエストを受け取り保持しておく
channelから値を読み出し、データベースに書き込み

**Comment by k-nasa** [comment]
雑なイメージ
```go
package main

import "log"

var hoge []int

func main() {
	resc := make(chan int, 8)

	go func(resc chan int) {

		for i := range resc {
			hoge = append(hoge, i)

			if len(hoge) >= 10 {
				log.Println("the main goroutine receives:", i)
				hoge = make([]int, 0)
			}
		}
	}(resc)

        // ココが実際にhttp requestを受けて、channelに送信するところ
	for i := 0; i < 99; i++ {
		resc <- i
	}
}
```

**Comment by ArkArk** [comment]
## 問題点

10個ずつさばく場合、`総request数 % 10`分のレポートが現れない

- レポート時にすべてのDBへのwriteが完了させておく必要がある
- あるいは、レポート時の集計率をSLIの一つにするという方針もある

**Comment by ArkArk** [comment]
実装が楽で問題点も特になさそうな

https://github.com/voyagegroup/hakaru201911-team-c/issues/17

を優先することにした。
